// Code generated by protoc-gen-go.
// source: osmsg.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	osmsg.proto

It has these top-level messages:
	OSMsg
	Msg
*/
package msg

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type OSMsg struct {
	Fromu            *string `protobuf:"bytes,1,req,name=fromu" json:"fromu,omitempty"`
	Tou              *string `protobuf:"bytes,2,opt,name=tou" json:"tou,omitempty"`
	Content          *string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OSMsg) Reset()         { *m = OSMsg{} }
func (m *OSMsg) String() string { return proto.CompactTextString(m) }
func (*OSMsg) ProtoMessage()    {}

func (m *OSMsg) GetFromu() string {
	if m != nil && m.Fromu != nil {
		return *m.Fromu
	}
	return ""
}

func (m *OSMsg) GetTou() string {
	if m != nil && m.Tou != nil {
		return *m.Tou
	}
	return ""
}

func (m *OSMsg) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type Msg struct {
	Fromu            *string `protobuf:"bytes,1,req,name=fromu" json:"fromu,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}

func (m *Msg) GetFromu() string {
	if m != nil && m.Fromu != nil {
		return *m.Fromu
	}
	return ""
}

func init() {
}
